---
- name: Configure web server
  hosts: webservers
  become: true

  roles:
    - webserver
    - node_exporter

- name: Configure monitoring server
  hosts: monitoring
  become: true

  roles:
    - prometheus
    - grafana
    - alertmanager
    - alert-webhook
